-- MySQL Script generated by MySQL Workbench
-- 06/04/14 14:45:13
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ortoba
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ortoba` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
-- -----------------------------------------------------
-- Schema ortoba
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ortoba` DEFAULT CHARACTER SET latin1 ;
USE `ortoba` ;

-- -----------------------------------------------------
-- Table `ortoba`.`city`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ortoba`.`city` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `nbMeeting` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

USE `ortoba` ;

-- -----------------------------------------------------
-- Table `ortoba`.`team`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ortoba`.`team` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `score` INT(11) NOT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_team_city1_idx` (`city_id` ASC),
  CONSTRAINT `fk_team_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `ortoba`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `ortoba`.`meeting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ortoba`.`meeting` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `scoreTeam1` INT(11) NOT NULL,
  `scoreTeam2` INT(11) NOT NULL,
  `teamId1` INT(11) NOT NULL,
  `teamId2` INT(11) NOT NULL,
  `city_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `teamId1` (`teamId1` ASC),
  INDEX `teamId2` (`teamId2` ASC),
  INDEX `fk_meeting_city1_idx` (`city_id` ASC),
  CONSTRAINT `fk_team_team2`
    FOREIGN KEY (`teamId2`)
    REFERENCES `ortoba`.`team` (`id`),
  CONSTRAINT `fk_team_team1`
    FOREIGN KEY (`teamId1`)
    REFERENCES `ortoba`.`team` (`id`),
  CONSTRAINT `fk_meeting_city1`
    FOREIGN KEY (`city_id`)
    REFERENCES `ortoba`.`city` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
USE `ortoba`;

DELIMITER $$
USE `ortoba`$$
CREATE TRIGGER `calcul_score` AFTER INSERT ON `meeting`
 FOR EACH ROW BEGIN
	IF NEW.scoreTeam1 > NEW.scoreTeam2 THEN
		UPDATE team
		SET score = score + 3
		WHERE id = NEW.teamId1;

		UPDATE team
		SET score = score + 1
		WHERE id = NEW.teamId2;

	ELSEIF NEW.scoreTeam1 < NEW.scoreTeam2 THEN
		UPDATE team
		SET score = score + 1
		WHERE id = NEW.teamId1;

		UPDATE team
		SET score = score + 3
		WHERE id = NEW.teamId2;

	ELSEIF NEW.scoreTeam1 = NEW.scoreTeam2 THEN
		UPDATE team
		SET score = score + 2
		WHERE id = NEW.teamId1;

		UPDATE team
		SET score = score + 2
		WHERE id = NEW.teamId2;
	END IF;
END$$


DELIMITER ;


DELIMITER $$
USE `ortoba`$$
CREATE TRIGGER `update_nbmetting` AFTER INSERT ON `meeting`
 FOR EACH ROW BEGIN
 	UPDATE city
 	SET nbMeeting = nbMeeting+1
 	WHERE id = NEW.city_id
END$$


DELIMITER ;